version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-mehmet}"
    image: data-preparation
    platform: linux/amd64
    container_name: data-preparation-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-mehmetalpay}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-mehmetalpay}/.config/gcloud
    ports:
      - 8888:8888

    ipc: host
    init: true


